### ISSUE TITLE
Add support for input of URLs

### ISSUE THREAD

**Issue by VaclavRut** [VaclavRut/actor-amazon-crawler#1]
To be able to add a link to:
 ```
{
  "url":"link",
  "label":"category" // item
}
```

And we will get all the items for given urls.

**Comment by ravishri1** [comment]
iam trying to use above . not working, plz help for category pages

> {
 "maxResults":400,   
 "url":"https://www.amazon.com/s/ref=lp_3760911_nr_n_0?fst=as%3Aoff&rh=n%3A3760911%2Cn%3A%2111055981%2Cn%3A11058281&bbn=11055981&ie=UTF8&qid=1567006815&rnid=11055981",
 "liveView": true,
 "apifyProxyGroups": ["RESIDENTIAL"] //optional
 }

>

**Comment by VaclavRut** [comment]
@ravishri1 I have added a function to add there a links directly to the input, so test it out and let me know
